### PR TITLE
scaffolding from mucrm boiler plate

### PR DESCRIPTION
**Pull request by peterghrong**
# Description

Scaffolding from flask boilerplate from mucrm.
1. Dockerised flask.
2. I sent the env file in the MADA general text channel. 
Fixes # (issue)
3. Instruction to setup is in the backend folder README

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.  
Provide instructions so we can **reproduce**.  
Please also list any relevant details for your test configuration

- `python manage.py --config development runserver`
- All other configurations are in the README
- db migration is not tested.

# Checklist:

- [ ] I have performed a self-review of my own code (can't read)
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I will rebase before merging

### CODE REVIEW

**Comment by kehwhy** [comment]
Looks good to me! I got the project set up with the docker image running on my device with no problems but let's wait for a second reviewer as well. Thank you so much!

**Review by kehwhy — APPROVED** [review]
Missing some newlines at the end of some files but set up went fine on my end! Let's wait for a second reviewer just in case.

**Comment by kehwhy** [comment]
Can you add pytest to the requirements.txt file as well? Thank you!

**Comment by peterghrong** [comment]
> Can you add pytest to the requirements.txt file as well? Thank you!

confirmed with katie that pytest wont be needed

**Pull request merged**
